### ISSUE TITLE
Site takes 5-7 seconds to load if AdBlocker EasyPrivacy list is enabled

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry.io#478] opened 2018-03-27 19:03 UTC
If the list [EasyPrivacy](https://easylist.to/) is enabled on the user browser AdBlock (Adblock Plus, AdBlock or uBlock Origin) the website takes about 5-7 seconds to load any page.

**Comment by maximest-pierre** [comment] 2018-03-27 19:53
This is probably caused by the facebook analytic and Google analytics.

**Comment by alyssaoc** [comment] 2018-10-18 20:12
closing, this is no longer an issue. repopen if necessary

**Closed by alyssaoc** 2018-10-18 20:12 UTC
Labels: area: devops, help wanted, level: 3, type: improvement
