### ISSUE TITLE
Implement "categories" functionality for "news" posts

### ISSUE THREAD

**Issue by Feanor78** [lbryio/lbry.io#291] opened 2017-12-14 20:07 UTC
Allow blog posts in the "news" section to be categorized like posts in the "bounty" section (https://lbry.io/bounty) and create RSS subscriptions/feeds for each category

**Comment by tzarebczan** [comment] 2017-12-14 22:05
@Feanor78 is this the same as https://github.com/lbryio/lbry.io/issues/290 ? Maybe expand on that one

**Comment by Feanor78** [comment] 2018-01-04 17:49
Yes, pretty much the same.

**Comment by kauffj** [comment] 2018-01-09 20:57
Duplicate of #290

**Closed by kauffj** 2018-01-09 20:57 UTC
